spring:
  application:
    name: myksBK
  profiles:
    active: dev

  ai:
    openai:

      api-key: ${OPENAI_API_KEY:test}

      # (선택) 모델 지정 가능 (기본값: gpt-3.5-turbo)
      chat:
        options:
          model: gpt-4o

# 배포 실행 명령어 예시
# java -jar -Dspring.profiles.active=prod myksBK-server.jar