spring:
  application:
    name: myksBK
  profiles:
    active: dev

  ai:
    openai:

      api-key: ${OPENAI_API_KEY:test}

      # (선택) 모델 지정 가능 (기본값: gpt-3.5-turbo)
      chat:
        options:
          model: gpt-4o

# 쿠키 설정
jwt:
  cookie:
    domain: null       # 로컬에서는 도메인 설정 없음 (자동으로 localhost 인식)
    secure: false      # HTTP 허용
    samesite: Lax      # 같은 도메인(localhost)끼리만 통신
  secret: 4612a10be28cdbb14c3be6b18e3396d902a4dcc967c733718d7b80092738551a
  access-exp-ms: 1800000      # 30분
  refresh-exp-ms: 1209600000  # 14일
  issuer: myks
  refresh-cookie-name: refreshToken

# 개발 서버 포트 설정
server:
  port: 8081

# 배포 실행 명령어 예시
# java -jar -Dspring.profiles.active=prod myksBK-server.jar