spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: jdbc:mysql://mykspj-mysql.cvacmycywd6n.ap-southeast-2.rds.amazonaws.com:3306/reactpj?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: admin
    password: dhksthghdck2
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

jwt:
  cookie:
    domain: .qqup.ai.kr  # 프론트/백엔드 도메인 공유
    secure: true         # HTTPS 필수
    samesite: None       # 크로스 도메인 허용
  secret: 4612a10be28cdbb14c3be6b18e3396d902a4dcc967c733718d7b80092738551a
  access-exp-ms: 1800000
  refresh-exp-ms: 1209600000
  issuer: myks
  refresh-cookie-name: refreshToken

# 서버 포트 설정 (Prod는 8080)
server:
  port: 8080